### ISSUE TITLE
[question] Is this the latest version?

### ISSUE THREAD

**Issue by yurivict** [nasa/PLEXIL5#3]
Sourceforge has 4.5.0RC2.
What is the version of this code here on GitHub?
Could you please tag it?

**Comment by cesaramh** [comment]
PLEXIL5 is a verification environment for PLEXIL. Five stands for Formal Interactive Verification Environment. It’s not a new version of PLEXIL. 

Sorry for the confusion,

--
Cesar

**Comment by yurivict** [comment]
Ok, thanks!
